#include "Autogen.h"

void vector_init(Vector *where) {
	where->size = 0;
	where->realsize = 1;
	where->arr = malloc(sizeof(Link));	
}

void vector_push(Vector *where, Link what) {
	if(where->realsize < where->size + 1) {
		where->realsize *= 2;
		where->arr = realloc(where->arr, where->realsize * sizeof(Link));
	}
	where->arr[where->size] = what;
	where->size += 1;
}

void vector_free(Vector *where) {
	free(where->arr);
}

void deinit_autogen() {
	for(int i = 0; i < stationlen; i++) {
		free(stations[i].boardInfo.exit);
		if(stations[i].boardInfo.transfer != NULL) {
			for(int k = 0; k < stations[i].boardInfo.transferlen; k++) {
				free(stations[i].boardInfo.transfer[k].pos);
			}
			free(stations[i].boardInfo.transfer);
		}
	}
	free(stations);
	for(int i = 0; i < stationlen; i++)
	{
		vector_free(links + i);
	}
	free(links);
    free(lines);
    free(graph_index);
}

void init_autogen() {
  lines = malloc(5 * sizeof(Line));
  lines[0].name = "Кировско-Выборгская";
  lines[0].color = GColorRed;
  lines[0].stations = 19;
  lines[0].startfrom = 0;
  lines[1].name = "Московско-Петроградская";
  lines[1].color = GColorBlue;
  lines[1].stations = 18;
  lines[1].startfrom = 19;
  lines[2].name = "Невско-Василеостровская";
  lines[2].color = GColorIslamicGreen;
  lines[2].stations = 10;
  lines[2].startfrom = 37;
  lines[3].name = "Правобережная";
  lines[3].color = GColorOrange;
  lines[3].stations = 8;
  lines[3].startfrom = 47;
  lines[4].name = "Фрунзенско-Приморская";
  lines[4].color = GColorPurple;
  lines[4].stations = 12;
  lines[4].startfrom = 55;

  stations = malloc(67 * sizeof(Station));
  stationlen = 67;
  stations[0].line = 0;
  stations[0].name = "Девяткино";
  stations[0].boardInfo.exit = malloc(3 * sizeof(int));
  stations[0].boardInfo.exitlen = 3;
  stations[0].boardInfo.exit[0] = 0;
  stations[0].boardInfo.exit[1] = 2;
  stations[0].boardInfo.exit[2] = 4;
  stations[0].boardInfo.transfer = NULL;
  stations[1].line = 0;
  stations[1].name = "Гражданский проспект";
  stations[1].boardInfo.exit = malloc(1 * sizeof(int));
  stations[1].boardInfo.exitlen = 1;
  stations[1].boardInfo.exit[0] = 4;
  stations[1].boardInfo.transfer = NULL;
  stations[2].line = 0;
  stations[2].name = "Академическая";
  stations[2].boardInfo.exit = malloc(1 * sizeof(int));
  stations[2].boardInfo.exitlen = 1;
  stations[2].boardInfo.exit[0] = 3;
  stations[2].boardInfo.transfer = NULL;
  stations[3].line = 0;
  stations[3].name = "Политехническая";
  stations[3].boardInfo.exit = malloc(1 * sizeof(int));
  stations[3].boardInfo.exitlen = 1;
  stations[3].boardInfo.exit[0] = 0;
  stations[3].boardInfo.transfer = NULL;
  stations[4].line = 0;
  stations[4].name = "Площадь Мужества";
  stations[4].boardInfo.exit = malloc(1 * sizeof(int));
  stations[4].boardInfo.exitlen = 1;
  stations[4].boardInfo.exit[0] = 0;
  stations[4].boardInfo.transfer = NULL;
  stations[5].line = 0;
  stations[5].name = "Лесная";
  stations[5].boardInfo.exit = malloc(1 * sizeof(int));
  stations[5].boardInfo.exitlen = 1;
  stations[5].boardInfo.exit[0] = 0;
  stations[5].boardInfo.transfer = NULL;
  stations[6].line = 0;
  stations[6].name = "Выборгская";
  stations[6].boardInfo.exit = malloc(1 * sizeof(int));
  stations[6].boardInfo.exitlen = 1;
  stations[6].boardInfo.exit[0] = 4;
  stations[6].boardInfo.transfer = NULL;
  stations[7].line = 0;
  stations[7].name = "Площадь Ленина";
  stations[7].boardInfo.exit = malloc(2 * sizeof(int));
  stations[7].boardInfo.exitlen = 2;
  stations[7].boardInfo.exit[0] = 1;
  stations[7].boardInfo.exit[1] = 3;
  stations[7].boardInfo.transfer = NULL;
  stations[8].line = 0;
  stations[8].name = "Чернышевская";
  stations[8].boardInfo.exit = malloc(1 * sizeof(int));
  stations[8].boardInfo.exitlen = 1;
  stations[8].boardInfo.exit[0] = 3;
  stations[8].boardInfo.transfer = NULL;
  stations[9].line = 0;
  stations[9].name = "Площадь Восстания";
  stations[9].boardInfo.exit = malloc(2 * sizeof(int));
  stations[9].boardInfo.exitlen = 2;
  stations[9].boardInfo.exit[0] = 1;
  stations[9].boardInfo.exit[1] = 3;
  stations[9].boardInfo.transfer = malloc(1 * sizeof(Transfer));
  stations[9].boardInfo.transferlen = 1;
  stations[9].boardInfo.transfer[0].prevStation = -1;
  stations[9].boardInfo.transfer[0].toStation = 40;
  stations[9].boardInfo.transfer[0].nextStation = -1;
  stations[9].boardInfo.transfer[0].pos = malloc(1 * sizeof(int));
  stations[9].boardInfo.transfer[0].poslen = 1;
  stations[9].boardInfo.transfer[0].pos[0] = 2;
  stations[10].line = 0;
  stations[10].name = "Владимирская";
  stations[10].boardInfo.exit = malloc(1 * sizeof(int));
  stations[10].boardInfo.exitlen = 1;
  stations[10].boardInfo.exit[0] = 4;
  stations[10].boardInfo.transfer = malloc(1 * sizeof(Transfer));
  stations[10].boardInfo.transferlen = 1;
  stations[10].boardInfo.transfer[0].prevStation = -1;
  stations[10].boardInfo.transfer[0].toStation = 48;
  stations[10].boardInfo.transfer[0].nextStation = -1;
  stations[10].boardInfo.transfer[0].pos = malloc(1 * sizeof(int));
  stations[10].boardInfo.transfer[0].poslen = 1;
  stations[10].boardInfo.transfer[0].pos[0] = 3;
  stations[11].line = 0;
  stations[11].name = "Пушкинская";
  stations[11].boardInfo.exit = malloc(1 * sizeof(int));
  stations[11].boardInfo.exitlen = 1;
  stations[11].boardInfo.exit[0] = 1;
  stations[11].boardInfo.transfer = malloc(1 * sizeof(Transfer));
  stations[11].boardInfo.transferlen = 1;
  stations[11].boardInfo.transfer[0].prevStation = -1;
  stations[11].boardInfo.transfer[0].toStation = 61;
  stations[11].boardInfo.transfer[0].nextStation = -1;
  stations[11].boardInfo.transfer[0].pos = malloc(1 * sizeof(int));
  stations[11].boardInfo.transfer[0].poslen = 1;
  stations[11].boardInfo.transfer[0].pos[0] = 2;
  stations[12].line = 0;
  stations[12].name = "Технологический институт - 1";
  stations[12].boardInfo.exit = malloc(1 * sizeof(int));
  stations[12].boardInfo.exitlen = 1;
  stations[12].boardInfo.exit[0] = 4;
  stations[12].boardInfo.transfer = malloc(4 * sizeof(Transfer));
  stations[12].boardInfo.transferlen = 4;
  stations[12].boardInfo.transfer[0].prevStation = 11;
  stations[12].boardInfo.transfer[0].toStation = 29;
  stations[12].boardInfo.transfer[0].nextStation = 30;
  stations[12].boardInfo.transfer[0].pos = malloc(2 * sizeof(int));
  stations[12].boardInfo.transfer[0].poslen = 2;
  stations[12].boardInfo.transfer[0].pos[0] = 1;
  stations[12].boardInfo.transfer[0].pos[1] = 3;
  stations[12].boardInfo.transfer[1].prevStation = 11;
  stations[12].boardInfo.transfer[1].toStation = 29;
  stations[12].boardInfo.transfer[1].nextStation = 28;
  stations[12].boardInfo.transfer[1].pos = malloc(1 * sizeof(int));
  stations[12].boardInfo.transfer[1].poslen = 1;
  stations[12].boardInfo.transfer[1].pos[0] = 2;
  stations[12].boardInfo.transfer[2].prevStation = 13;
  stations[12].boardInfo.transfer[2].toStation = 29;
  stations[12].boardInfo.transfer[2].nextStation = 30;
  stations[12].boardInfo.transfer[2].pos = malloc(1 * sizeof(int));
  stations[12].boardInfo.transfer[2].poslen = 1;
  stations[12].boardInfo.transfer[2].pos[0] = 1;
  stations[12].boardInfo.transfer[3].prevStation = 13;
  stations[12].boardInfo.transfer[3].toStation = 29;
  stations[12].boardInfo.transfer[3].nextStation = 28;
  stations[12].boardInfo.transfer[3].pos = malloc(2 * sizeof(int));
  stations[12].boardInfo.transfer[3].poslen = 2;
  stations[12].boardInfo.transfer[3].pos[0] = 1;
  stations[12].boardInfo.transfer[3].pos[1] = 3;
  stations[13].line = 0;
  stations[13].name = "Балтийская";
  stations[13].boardInfo.exit = malloc(1 * sizeof(int));
  stations[13].boardInfo.exitlen = 1;
  stations[13].boardInfo.exit[0] = 0;
  stations[13].boardInfo.transfer = NULL;
  stations[14].line = 0;
  stations[14].name = "Нарвская";
  stations[14].boardInfo.exit = malloc(1 * sizeof(int));
  stations[14].boardInfo.exitlen = 1;
  stations[14].boardInfo.exit[0] = 3;
  stations[14].boardInfo.transfer = NULL;
  stations[15].line = 0;
  stations[15].name = "Кировский завод";
  stations[15].boardInfo.exit = malloc(1 * sizeof(int));
  stations[15].boardInfo.exitlen = 1;
  stations[15].boardInfo.exit[0] = 4;
  stations[15].boardInfo.transfer = NULL;
  stations[16].line = 0;
  stations[16].name = "Автово";
  stations[16].boardInfo.exit = malloc(1 * sizeof(int));
  stations[16].boardInfo.exitlen = 1;
  stations[16].boardInfo.exit[0] = 4;
  stations[16].boardInfo.transfer = NULL;
  stations[17].line = 0;
  stations[17].name = "Ленинский проспект";
  stations[17].boardInfo.exit = malloc(2 * sizeof(int));
  stations[17].boardInfo.exitlen = 2;
  stations[17].boardInfo.exit[0] = 0;
  stations[17].boardInfo.exit[1] = 4;
  stations[17].boardInfo.transfer = NULL;
  stations[18].line = 0;
  stations[18].name = "Проспект Ветеранов";
  stations[18].boardInfo.exit = malloc(2 * sizeof(int));
  stations[18].boardInfo.exitlen = 2;
  stations[18].boardInfo.exit[0] = 0;
  stations[18].boardInfo.exit[1] = 4;
  stations[18].boardInfo.transfer = NULL;
  stations[19].line = 1;
  stations[19].name = "Парнас";
  stations[19].boardInfo.exit = malloc(1 * sizeof(int));
  stations[19].boardInfo.exitlen = 1;
  stations[19].boardInfo.exit[0] = 2;
  stations[19].boardInfo.transfer = NULL;
  stations[20].line = 1;
  stations[20].name = "Проспект Просвещения";
  stations[20].boardInfo.exit = malloc(1 * sizeof(int));
  stations[20].boardInfo.exitlen = 1;
  stations[20].boardInfo.exit[0] = 4;
  stations[20].boardInfo.transfer = NULL;
  stations[21].line = 1;
  stations[21].name = "Озерки";
  stations[21].boardInfo.exit = malloc(1 * sizeof(int));
  stations[21].boardInfo.exitlen = 1;
  stations[21].boardInfo.exit[0] = 4;
  stations[21].boardInfo.transfer = NULL;
  stations[22].line = 1;
  stations[22].name = "Удельная";
  stations[22].boardInfo.exit = malloc(1 * sizeof(int));
  stations[22].boardInfo.exitlen = 1;
  stations[22].boardInfo.exit[0] = 0;
  stations[22].boardInfo.transfer = NULL;
  stations[23].line = 1;
  stations[23].name = "Пионерская";
  stations[23].boardInfo.exit = malloc(1 * sizeof(int));
  stations[23].boardInfo.exitlen = 1;
  stations[23].boardInfo.exit[0] = 0;
  stations[23].boardInfo.transfer = NULL;
  stations[24].line = 1;
  stations[24].name = "Чёрная речка";
  stations[24].boardInfo.exit = malloc(1 * sizeof(int));
  stations[24].boardInfo.exitlen = 1;
  stations[24].boardInfo.exit[0] = 0;
  stations[24].boardInfo.transfer = NULL;
  stations[25].line = 1;
  stations[25].name = "Петроградская";
  stations[25].boardInfo.exit = malloc(1 * sizeof(int));
  stations[25].boardInfo.exitlen = 1;
  stations[25].boardInfo.exit[0] = 4;
  stations[25].boardInfo.transfer = NULL;
  stations[26].line = 1;
  stations[26].name = "Горьковская";
  stations[26].boardInfo.exit = malloc(1 * sizeof(int));
  stations[26].boardInfo.exitlen = 1;
  stations[26].boardInfo.exit[0] = 3;
  stations[26].boardInfo.transfer = NULL;
  stations[27].line = 1;
  stations[27].name = "Невский проспект";
  stations[27].boardInfo.exit = malloc(2 * sizeof(int));
  stations[27].boardInfo.exitlen = 2;
  stations[27].boardInfo.exit[0] = 1;
  stations[27].boardInfo.exit[1] = 3;
  stations[27].boardInfo.transfer = malloc(1 * sizeof(Transfer));
  stations[27].boardInfo.transferlen = 1;
  stations[27].boardInfo.transfer[0].prevStation = -1;
  stations[27].boardInfo.transfer[0].toStation = 39;
  stations[27].boardInfo.transfer[0].nextStation = -1;
  stations[27].boardInfo.transfer[0].pos = malloc(1 * sizeof(int));
  stations[27].boardInfo.transfer[0].poslen = 1;
  stations[27].boardInfo.transfer[0].pos[0] = 3;
  stations[28].line = 1;
  stations[28].name = "Сенная площадь";
  stations[28].boardInfo.exit = malloc(1 * sizeof(int));
  stations[28].boardInfo.exitlen = 1;
  stations[28].boardInfo.exit[0] = 3;
  stations[28].boardInfo.transfer = malloc(2 * sizeof(Transfer));
  stations[28].boardInfo.transferlen = 2;
  stations[28].boardInfo.transfer[0].prevStation = -1;
  stations[28].boardInfo.transfer[0].toStation = 47;
  stations[28].boardInfo.transfer[0].nextStation = -1;
  stations[28].boardInfo.transfer[0].pos = malloc(1 * sizeof(int));
  stations[28].boardInfo.transfer[0].poslen = 1;
  stations[28].boardInfo.transfer[0].pos[0] = 0;
  stations[28].boardInfo.transfer[1].prevStation = -1;
  stations[28].boardInfo.transfer[1].toStation = 60;
  stations[28].boardInfo.transfer[1].nextStation = -1;
  stations[28].boardInfo.transfer[1].pos = malloc(1 * sizeof(int));
  stations[28].boardInfo.transfer[1].poslen = 1;
  stations[28].boardInfo.transfer[1].pos[0] = 2;
  stations[29].line = 1;
  stations[29].name = "Технологический институт - 2";
  stations[29].boardInfo.exit = malloc(1 * sizeof(int));
  stations[29].boardInfo.exitlen = 1;
  stations[29].boardInfo.exit[0] = 4;
  stations[29].boardInfo.transfer = malloc(4 * sizeof(Transfer));
  stations[29].boardInfo.transferlen = 4;
  stations[29].boardInfo.transfer[0].prevStation = 28;
  stations[29].boardInfo.transfer[0].toStation = 12;
  stations[29].boardInfo.transfer[0].nextStation = 13;
  stations[29].boardInfo.transfer[0].pos = malloc(2 * sizeof(int));
  stations[29].boardInfo.transfer[0].poslen = 2;
  stations[29].boardInfo.transfer[0].pos[0] = 1;
  stations[29].boardInfo.transfer[0].pos[1] = 3;
  stations[29].boardInfo.transfer[1].prevStation = 28;
  stations[29].boardInfo.transfer[1].toStation = 12;
  stations[29].boardInfo.transfer[1].nextStation = 11;
  stations[29].boardInfo.transfer[1].pos = malloc(2 * sizeof(int));
  stations[29].boardInfo.transfer[1].poslen = 2;
  stations[29].boardInfo.transfer[1].pos[0] = 1;
  stations[29].boardInfo.transfer[1].pos[1] = 3;
  stations[29].boardInfo.transfer[2].prevStation = 30;
  stations[29].boardInfo.transfer[2].toStation = 12;
  stations[29].boardInfo.transfer[2].nextStation = 13;
  stations[29].boardInfo.transfer[2].pos = malloc(1 * sizeof(int));
  stations[29].boardInfo.transfer[2].poslen = 1;
  stations[29].boardInfo.transfer[2].pos[0] = 2;
  stations[29].boardInfo.transfer[3].prevStation = 30;
  stations[29].boardInfo.transfer[3].toStation = 12;
  stations[29].boardInfo.transfer[3].nextStation = 11;
  stations[29].boardInfo.transfer[3].pos = malloc(3 * sizeof(int));
  stations[29].boardInfo.transfer[3].poslen = 3;
  stations[29].boardInfo.transfer[3].pos[0] = 1;
  stations[29].boardInfo.transfer[3].pos[1] = 2;
  stations[29].boardInfo.transfer[3].pos[2] = 4;
  stations[30].line = 1;
  stations[30].name = "Фрунзенская";
  stations[30].boardInfo.exit = malloc(1 * sizeof(int));
  stations[30].boardInfo.exitlen = 1;
  stations[30].boardInfo.exit[0] = 3;
  stations[30].boardInfo.transfer = NULL;
  stations[31].line = 1;
  stations[31].name = "Московские ворота";
  stations[31].boardInfo.exit = malloc(1 * sizeof(int));
  stations[31].boardInfo.exitlen = 1;
  stations[31].boardInfo.exit[0] = 1;
  stations[31].boardInfo.transfer = NULL;
  stations[32].line = 1;
  stations[32].name = "Электросила";
  stations[32].boardInfo.exit = malloc(1 * sizeof(int));
  stations[32].boardInfo.exitlen = 1;
  stations[32].boardInfo.exit[0] = 1;
  stations[32].boardInfo.transfer = NULL;
  stations[33].line = 1;
  stations[33].name = "Парк Победы";
  stations[33].boardInfo.exit = malloc(1 * sizeof(int));
  stations[33].boardInfo.exitlen = 1;
  stations[33].boardInfo.exit[0] = 0;
  stations[33].boardInfo.transfer = NULL;
  stations[34].line = 1;
  stations[34].name = "Московская";
  stations[34].boardInfo.exit = malloc(2 * sizeof(int));
  stations[34].boardInfo.exitlen = 2;
  stations[34].boardInfo.exit[0] = 0;
  stations[34].boardInfo.exit[1] = 4;
  stations[34].boardInfo.transfer = NULL;
  stations[35].line = 1;
  stations[35].name = "Звёздная";
  stations[35].boardInfo.exit = malloc(1 * sizeof(int));
  stations[35].boardInfo.exitlen = 1;
  stations[35].boardInfo.exit[0] = 4;
  stations[35].boardInfo.transfer = NULL;
  stations[36].line = 1;
  stations[36].name = "Купчино";
  stations[36].boardInfo.exit = malloc(4 * sizeof(int));
  stations[36].boardInfo.exitlen = 4;
  stations[36].boardInfo.exit[0] = 0;
  stations[36].boardInfo.exit[1] = 1;
  stations[36].boardInfo.exit[2] = 3;
  stations[36].boardInfo.exit[3] = 4;
  stations[36].boardInfo.transfer = NULL;
  stations[37].line = 2;
  stations[37].name = "Приморская";
  stations[37].boardInfo.exit = malloc(1 * sizeof(int));
  stations[37].boardInfo.exitlen = 1;
  stations[37].boardInfo.exit[0] = 4;
  stations[37].boardInfo.transfer = NULL;
  stations[38].line = 2;
  stations[38].name = "Василеостровская";
  stations[38].boardInfo.exit = malloc(1 * sizeof(int));
  stations[38].boardInfo.exitlen = 1;
  stations[38].boardInfo.exit[0] = 0;
  stations[38].boardInfo.transfer = NULL;
  stations[39].line = 2;
  stations[39].name = "Гостиный двор";
  stations[39].boardInfo.exit = malloc(2 * sizeof(int));
  stations[39].boardInfo.exitlen = 2;
  stations[39].boardInfo.exit[0] = 0;
  stations[39].boardInfo.exit[1] = 4;
  stations[39].boardInfo.transfer = malloc(1 * sizeof(Transfer));
  stations[39].boardInfo.transferlen = 1;
  stations[39].boardInfo.transfer[0].prevStation = -1;
  stations[39].boardInfo.transfer[0].toStation = 27;
  stations[39].boardInfo.transfer[0].nextStation = -1;
  stations[39].boardInfo.transfer[0].pos = malloc(2 * sizeof(int));
  stations[39].boardInfo.transfer[0].poslen = 2;
  stations[39].boardInfo.transfer[0].pos[0] = 1;
  stations[39].boardInfo.transfer[0].pos[1] = 3;
  stations[40].line = 2;
  stations[40].name = "Маяковская";
  stations[40].boardInfo.exit = malloc(1 * sizeof(int));
  stations[40].boardInfo.exitlen = 1;
  stations[40].boardInfo.exit[0] = 4;
  stations[40].boardInfo.transfer = malloc(1 * sizeof(Transfer));
  stations[40].boardInfo.transferlen = 1;
  stations[40].boardInfo.transfer[0].prevStation = -1;
  stations[40].boardInfo.transfer[0].toStation = 9;
  stations[40].boardInfo.transfer[0].nextStation = -1;
  stations[40].boardInfo.transfer[0].pos = malloc(2 * sizeof(int));
  stations[40].boardInfo.transfer[0].poslen = 2;
  stations[40].boardInfo.transfer[0].pos[0] = 1;
  stations[40].boardInfo.transfer[0].pos[1] = 3;
  stations[41].line = 2;
  stations[41].name = "Площадь Александра Невского - 1";
  stations[41].boardInfo.exit = malloc(1 * sizeof(int));
  stations[41].boardInfo.exitlen = 1;
  stations[41].boardInfo.exit[0] = 4;
  stations[41].boardInfo.transfer = malloc(1 * sizeof(Transfer));
  stations[41].boardInfo.transferlen = 1;
  stations[41].boardInfo.transfer[0].prevStation = -1;
  stations[41].boardInfo.transfer[0].toStation = 50;
  stations[41].boardInfo.transfer[0].nextStation = -1;
  stations[41].boardInfo.transfer[0].pos = malloc(1 * sizeof(int));
  stations[41].boardInfo.transfer[0].poslen = 1;
  stations[41].boardInfo.transfer[0].pos[0] = 0;
  stations[42].line = 2;
  stations[42].name = "Елизаровская";
  stations[42].boardInfo.exit = malloc(1 * sizeof(int));
  stations[42].boardInfo.exitlen = 1;
  stations[42].boardInfo.exit[0] = 0;
  stations[42].boardInfo.transfer = NULL;
  stations[43].line = 2;
  stations[43].name = "Ломоносовская";
  stations[43].boardInfo.exit = malloc(1 * sizeof(int));
  stations[43].boardInfo.exitlen = 1;
  stations[43].boardInfo.exit[0] = 0;
  stations[43].boardInfo.transfer = NULL;
  stations[44].line = 2;
  stations[44].name = "Пролетарская";
  stations[44].boardInfo.exit = malloc(1 * sizeof(int));
  stations[44].boardInfo.exitlen = 1;
  stations[44].boardInfo.exit[0] = 1;
  stations[44].boardInfo.transfer = NULL;
  stations[45].line = 2;
  stations[45].name = "Обухово";
  stations[45].boardInfo.exit = malloc(1 * sizeof(int));
  stations[45].boardInfo.exitlen = 1;
  stations[45].boardInfo.exit[0] = 0;
  stations[45].boardInfo.transfer = NULL;
  stations[46].line = 2;
  stations[46].name = "Рыбацкое";
  stations[46].boardInfo.exit = malloc(3 * sizeof(int));
  stations[46].boardInfo.exitlen = 3;
  stations[46].boardInfo.exit[0] = 0;
  stations[46].boardInfo.exit[1] = 2;
  stations[46].boardInfo.exit[2] = 3;
  stations[46].boardInfo.transfer = NULL;
  stations[47].line = 3;
  stations[47].name = "Спасская";
  stations[47].boardInfo.exit = malloc(2 * sizeof(int));
  stations[47].boardInfo.exitlen = 2;
  stations[47].boardInfo.exit[0] = 0;
  stations[47].boardInfo.exit[1] = 4;
  stations[47].boardInfo.transfer = malloc(2 * sizeof(Transfer));
  stations[47].boardInfo.transferlen = 2;
  stations[47].boardInfo.transfer[0].prevStation = -1;
  stations[47].boardInfo.transfer[0].toStation = 28;
  stations[47].boardInfo.transfer[0].nextStation = -1;
  stations[47].boardInfo.transfer[0].pos = malloc(1 * sizeof(int));
  stations[47].boardInfo.transfer[0].poslen = 1;
  stations[47].boardInfo.transfer[0].pos[0] = 0;
  stations[47].boardInfo.transfer[1].prevStation = -1;
  stations[47].boardInfo.transfer[1].toStation = 60;
  stations[47].boardInfo.transfer[1].nextStation = -1;
  stations[47].boardInfo.transfer[1].pos = malloc(1 * sizeof(int));
  stations[47].boardInfo.transfer[1].poslen = 1;
  stations[47].boardInfo.transfer[1].pos[0] = 4;
  stations[48].line = 3;
  stations[48].name = "Достоевская";
  stations[48].boardInfo.exit = malloc(1 * sizeof(int));
  stations[48].boardInfo.exitlen = 1;
  stations[48].boardInfo.exit[0] = 3;
  stations[48].boardInfo.transfer = malloc(1 * sizeof(Transfer));
  stations[48].boardInfo.transferlen = 1;
  stations[48].boardInfo.transfer[0].prevStation = -1;
  stations[48].boardInfo.transfer[0].toStation = 10;
  stations[48].boardInfo.transfer[0].nextStation = -1;
  stations[48].boardInfo.transfer[0].pos = malloc(1 * sizeof(int));
  stations[48].boardInfo.transfer[0].poslen = 1;
  stations[48].boardInfo.transfer[0].pos[0] = 0;
  stations[49].line = 3;
  stations[49].name = "Лиговский проспект";
  stations[49].boardInfo.exit = malloc(1 * sizeof(int));
  stations[49].boardInfo.exitlen = 1;
  stations[49].boardInfo.exit[0] = 4;
  stations[49].boardInfo.transfer = NULL;
  stations[50].line = 3;
  stations[50].name = "Площадь Александра Невского - 2";
  stations[50].boardInfo.exit = malloc(1 * sizeof(int));
  stations[50].boardInfo.exitlen = 1;
  stations[50].boardInfo.exit[0] = 4;
  stations[50].boardInfo.transfer = malloc(1 * sizeof(Transfer));
  stations[50].boardInfo.transferlen = 1;
  stations[50].boardInfo.transfer[0].prevStation = -1;
  stations[50].boardInfo.transfer[0].toStation = 41;
  stations[50].boardInfo.transfer[0].nextStation = -1;
  stations[50].boardInfo.transfer[0].pos = malloc(1 * sizeof(int));
  stations[50].boardInfo.transfer[0].poslen = 1;
  stations[50].boardInfo.transfer[0].pos[0] = 0;
  stations[51].line = 3;
  stations[51].name = "Новочеркасская";
  stations[51].boardInfo.exit = malloc(1 * sizeof(int));
  stations[51].boardInfo.exitlen = 1;
  stations[51].boardInfo.exit[0] = 4;
  stations[51].boardInfo.transfer = NULL;
  stations[52].line = 3;
  stations[52].name = "Ладожская";
  stations[52].boardInfo.exit = malloc(1 * sizeof(int));
  stations[52].boardInfo.exitlen = 1;
  stations[52].boardInfo.exit[0] = 4;
  stations[52].boardInfo.transfer = NULL;
  stations[53].line = 3;
  stations[53].name = "Проспект Большевиков";
  stations[53].boardInfo.exit = malloc(1 * sizeof(int));
  stations[53].boardInfo.exitlen = 1;
  stations[53].boardInfo.exit[0] = 0;
  stations[53].boardInfo.transfer = NULL;
  stations[54].line = 3;
  stations[54].name = "Улица Дыбенко";
  stations[54].boardInfo.exit = malloc(1 * sizeof(int));
  stations[54].boardInfo.exitlen = 1;
  stations[54].boardInfo.exit[0] = 0;
  stations[54].boardInfo.transfer = NULL;
  stations[55].line = 4;
  stations[55].name = "Комендантский проспект";
  stations[55].boardInfo.exit = malloc(1 * sizeof(int));
  stations[55].boardInfo.exitlen = 1;
  stations[55].boardInfo.exit[0] = 0;
  stations[55].boardInfo.transfer = NULL;
  stations[56].line = 4;
  stations[56].name = "Старая Деревня";
  stations[56].boardInfo.exit = malloc(1 * sizeof(int));
  stations[56].boardInfo.exitlen = 1;
  stations[56].boardInfo.exit[0] = 4;
  stations[56].boardInfo.transfer = NULL;
  stations[57].line = 4;
  stations[57].name = "Крестовский остров";
  stations[57].boardInfo.exit = malloc(1 * sizeof(int));
  stations[57].boardInfo.exitlen = 1;
  stations[57].boardInfo.exit[0] = 4;
  stations[57].boardInfo.transfer = NULL;
  stations[58].line = 4;
  stations[58].name = "Чкаловская";
  stations[58].boardInfo.exit = malloc(1 * sizeof(int));
  stations[58].boardInfo.exitlen = 1;
  stations[58].boardInfo.exit[0] = 4;
  stations[58].boardInfo.transfer = NULL;
  stations[59].line = 4;
  stations[59].name = "Спортивная";
  stations[59].boardInfo.exit = malloc(2 * sizeof(int));
  stations[59].boardInfo.exitlen = 2;
  stations[59].boardInfo.exit[0] = 0;
  stations[59].boardInfo.exit[1] = 3;
  stations[59].boardInfo.transfer = NULL;
  stations[64].line = 4;
  stations[64].name = "Адмиралтейская";
  stations[64].boardInfo.exit = malloc(1 * sizeof(int));
  stations[64].boardInfo.exitlen = 1;
  stations[64].boardInfo.exit[0] = 0;
  stations[64].boardInfo.transfer = NULL;
  stations[60].line = 4;
  stations[60].name = "Садовая";
  stations[60].boardInfo.exit = malloc(1 * sizeof(int));
  stations[60].boardInfo.exitlen = 1;
  stations[60].boardInfo.exit[0] = 4;
  stations[60].boardInfo.transfer = malloc(2 * sizeof(Transfer));
  stations[60].boardInfo.transferlen = 2;
  stations[60].boardInfo.transfer[0].prevStation = -1;
  stations[60].boardInfo.transfer[0].toStation = 28;
  stations[60].boardInfo.transfer[0].nextStation = -1;
  stations[60].boardInfo.transfer[0].pos = malloc(1 * sizeof(int));
  stations[60].boardInfo.transfer[0].poslen = 1;
  stations[60].boardInfo.transfer[0].pos[0] = 0;
  stations[60].boardInfo.transfer[1].prevStation = -1;
  stations[60].boardInfo.transfer[1].toStation = 47;
  stations[60].boardInfo.transfer[1].nextStation = -1;
  stations[60].boardInfo.transfer[1].pos = malloc(2 * sizeof(int));
  stations[60].boardInfo.transfer[1].poslen = 2;
  stations[60].boardInfo.transfer[1].pos[0] = 1;
  stations[60].boardInfo.transfer[1].pos[1] = 3;
  stations[61].line = 4;
  stations[61].name = "Звенигородская";
  stations[61].boardInfo.exit = malloc(1 * sizeof(int));
  stations[61].boardInfo.exitlen = 1;
  stations[61].boardInfo.exit[0] = 1;
  stations[61].boardInfo.transfer = malloc(1 * sizeof(Transfer));
  stations[61].boardInfo.transferlen = 1;
  stations[61].boardInfo.transfer[0].prevStation = -1;
  stations[61].boardInfo.transfer[0].toStation = 11;
  stations[61].boardInfo.transfer[0].nextStation = -1;
  stations[61].boardInfo.transfer[0].pos = malloc(2 * sizeof(int));
  stations[61].boardInfo.transfer[0].poslen = 2;
  stations[61].boardInfo.transfer[0].pos[0] = 2;
  stations[61].boardInfo.transfer[0].pos[1] = 3;
  stations[63].line = 4;
  stations[63].name = "Обводный канал";
  stations[63].boardInfo.exit = malloc(1 * sizeof(int));
  stations[63].boardInfo.exitlen = 1;
  stations[63].boardInfo.exit[0] = 4;
  stations[63].boardInfo.transfer = NULL;
  stations[62].line = 4;
  stations[62].name = "Волковская";
  stations[62].boardInfo.exit = malloc(1 * sizeof(int));
  stations[62].boardInfo.exitlen = 1;
  stations[62].boardInfo.exit[0] = 1;
  stations[62].boardInfo.transfer = NULL;
  stations[65].line = 4;
  stations[65].name = "Бухарестская";
  stations[65].boardInfo.exit = malloc(1 * sizeof(int));
  stations[65].boardInfo.exitlen = 1;
  stations[65].boardInfo.exit[0] = 2;
  stations[65].boardInfo.transfer = NULL;
  stations[66].line = 4;
  stations[66].name = "Международная";
  stations[66].boardInfo.exit = malloc(1 * sizeof(int));
  stations[66].boardInfo.exitlen = 1;
  stations[66].boardInfo.exit[0] = 3;
  stations[66].boardInfo.transfer = NULL;

  links = malloc(67 * sizeof(Vector));
  for(int i = 0; i < 67; i++) {
    vector_init(links + i);
  }

  vector_push(links + 0, (Link) {.to = 1, .weight = 180});
  vector_push(links + 1, (Link) {.to = 0, .weight = 180});
  vector_push(links + 1, (Link) {.to = 2, .weight = 180});
  vector_push(links + 2, (Link) {.to = 1, .weight = 180});
  vector_push(links + 2, (Link) {.to = 3, .weight = 120});
  vector_push(links + 3, (Link) {.to = 2, .weight = 120});
  vector_push(links + 3, (Link) {.to = 4, .weight = 180});
  vector_push(links + 4, (Link) {.to = 3, .weight = 180});
  vector_push(links + 4, (Link) {.to = 5, .weight = 180});
  vector_push(links + 5, (Link) {.to = 4, .weight = 180});
  vector_push(links + 5, (Link) {.to = 6, .weight = 180});
  vector_push(links + 6, (Link) {.to = 5, .weight = 180});
  vector_push(links + 6, (Link) {.to = 7, .weight = 120});
  vector_push(links + 7, (Link) {.to = 6, .weight = 120});
  vector_push(links + 7, (Link) {.to = 8, .weight = 180});
  vector_push(links + 8, (Link) {.to = 7, .weight = 180});
  vector_push(links + 8, (Link) {.to = 9, .weight = 120});
  vector_push(links + 9, (Link) {.to = 8, .weight = 120});
  vector_push(links + 9, (Link) {.to = 40, .weight = 120});
  vector_push(links + 40, (Link) {.to = 9, .weight = 120});
  vector_push(links + 9, (Link) {.to = 10, .weight = 120});
  vector_push(links + 10, (Link) {.to = 9, .weight = 120});
  vector_push(links + 10, (Link) {.to = 11, .weight = 120});
  vector_push(links + 11, (Link) {.to = 10, .weight = 120});
  vector_push(links + 10, (Link) {.to = 48, .weight = 120});
  vector_push(links + 48, (Link) {.to = 10, .weight = 120});
  vector_push(links + 11, (Link) {.to = 61, .weight = 120});
  vector_push(links + 61, (Link) {.to = 11, .weight = 120});
  vector_push(links + 11, (Link) {.to = 12, .weight = 120});
  vector_push(links + 12, (Link) {.to = 11, .weight = 120});
  vector_push(links + 12, (Link) {.to = 13, .weight = 120});
  vector_push(links + 13, (Link) {.to = 12, .weight = 120});
  vector_push(links + 12, (Link) {.to = 29, .weight = 60});
  vector_push(links + 29, (Link) {.to = 12, .weight = 60});
  vector_push(links + 13, (Link) {.to = 14, .weight = 180});
  vector_push(links + 14, (Link) {.to = 13, .weight = 180});
  vector_push(links + 14, (Link) {.to = 15, .weight = 240});
  vector_push(links + 15, (Link) {.to = 14, .weight = 240});
  vector_push(links + 15, (Link) {.to = 16, .weight = 120});
  vector_push(links + 16, (Link) {.to = 15, .weight = 120});
  vector_push(links + 16, (Link) {.to = 17, .weight = 180});
  vector_push(links + 17, (Link) {.to = 16, .weight = 180});
  vector_push(links + 17, (Link) {.to = 18, .weight = 120});
  vector_push(links + 18, (Link) {.to = 17, .weight = 120});
  vector_push(links + 19, (Link) {.to = 20, .weight = 180});
  vector_push(links + 20, (Link) {.to = 19, .weight = 180});
  vector_push(links + 20, (Link) {.to = 21, .weight = 120});
  vector_push(links + 21, (Link) {.to = 20, .weight = 120});
  vector_push(links + 21, (Link) {.to = 22, .weight = 180});
  vector_push(links + 22, (Link) {.to = 21, .weight = 180});
  vector_push(links + 22, (Link) {.to = 23, .weight = 180});
  vector_push(links + 23, (Link) {.to = 22, .weight = 180});
  vector_push(links + 23, (Link) {.to = 24, .weight = 180});
  vector_push(links + 24, (Link) {.to = 23, .weight = 180});
  vector_push(links + 24, (Link) {.to = 25, .weight = 240});
  vector_push(links + 25, (Link) {.to = 24, .weight = 240});
  vector_push(links + 25, (Link) {.to = 26, .weight = 120});
  vector_push(links + 26, (Link) {.to = 25, .weight = 120});
  vector_push(links + 26, (Link) {.to = 27, .weight = 240});
  vector_push(links + 27, (Link) {.to = 26, .weight = 240});
  vector_push(links + 27, (Link) {.to = 39, .weight = 120});
  vector_push(links + 39, (Link) {.to = 27, .weight = 120});
  vector_push(links + 27, (Link) {.to = 28, .weight = 120});
  vector_push(links + 28, (Link) {.to = 27, .weight = 120});
  vector_push(links + 28, (Link) {.to = 60, .weight = 180});
  vector_push(links + 60, (Link) {.to = 28, .weight = 180});
  vector_push(links + 28, (Link) {.to = 47, .weight = 180});
  vector_push(links + 47, (Link) {.to = 28, .weight = 180});
  vector_push(links + 28, (Link) {.to = 29, .weight = 180});
  vector_push(links + 29, (Link) {.to = 28, .weight = 180});
  vector_push(links + 29, (Link) {.to = 30, .weight = 120});
  vector_push(links + 30, (Link) {.to = 29, .weight = 120});
  vector_push(links + 30, (Link) {.to = 31, .weight = 120});
  vector_push(links + 31, (Link) {.to = 30, .weight = 120});
  vector_push(links + 31, (Link) {.to = 32, .weight = 120});
  vector_push(links + 32, (Link) {.to = 31, .weight = 120});
  vector_push(links + 32, (Link) {.to = 33, .weight = 120});
  vector_push(links + 33, (Link) {.to = 32, .weight = 120});
  vector_push(links + 33, (Link) {.to = 34, .weight = 180});
  vector_push(links + 34, (Link) {.to = 33, .weight = 180});
  vector_push(links + 34, (Link) {.to = 35, .weight = 240});
  vector_push(links + 35, (Link) {.to = 34, .weight = 240});
  vector_push(links + 35, (Link) {.to = 36, .weight = 180});
  vector_push(links + 36, (Link) {.to = 35, .weight = 180});
  vector_push(links + 37, (Link) {.to = 38, .weight = 240});
  vector_push(links + 38, (Link) {.to = 37, .weight = 240});
  vector_push(links + 38, (Link) {.to = 39, .weight = 240});
  vector_push(links + 39, (Link) {.to = 38, .weight = 240});
  vector_push(links + 39, (Link) {.to = 40, .weight = 180});
  vector_push(links + 40, (Link) {.to = 39, .weight = 180});
  vector_push(links + 40, (Link) {.to = 41, .weight = 180});
  vector_push(links + 41, (Link) {.to = 40, .weight = 180});
  vector_push(links + 41, (Link) {.to = 42, .weight = 300});
  vector_push(links + 42, (Link) {.to = 41, .weight = 300});
  vector_push(links + 41, (Link) {.to = 50, .weight = 120});
  vector_push(links + 50, (Link) {.to = 41, .weight = 120});
  vector_push(links + 42, (Link) {.to = 43, .weight = 180});
  vector_push(links + 43, (Link) {.to = 42, .weight = 180});
  vector_push(links + 43, (Link) {.to = 44, .weight = 180});
  vector_push(links + 44, (Link) {.to = 43, .weight = 180});
  vector_push(links + 44, (Link) {.to = 45, .weight = 180});
  vector_push(links + 45, (Link) {.to = 44, .weight = 180});
  vector_push(links + 45, (Link) {.to = 46, .weight = 240});
  vector_push(links + 46, (Link) {.to = 45, .weight = 240});
  vector_push(links + 47, (Link) {.to = 60, .weight = 180});
  vector_push(links + 60, (Link) {.to = 47, .weight = 180});
  vector_push(links + 47, (Link) {.to = 48, .weight = 240});
  vector_push(links + 48, (Link) {.to = 47, .weight = 240});
  vector_push(links + 48, (Link) {.to = 49, .weight = 120});
  vector_push(links + 49, (Link) {.to = 48, .weight = 120});
  vector_push(links + 49, (Link) {.to = 50, .weight = 120});
  vector_push(links + 50, (Link) {.to = 49, .weight = 120});
  vector_push(links + 50, (Link) {.to = 51, .weight = 180});
  vector_push(links + 51, (Link) {.to = 50, .weight = 180});
  vector_push(links + 51, (Link) {.to = 52, .weight = 180});
  vector_push(links + 52, (Link) {.to = 51, .weight = 180});
  vector_push(links + 52, (Link) {.to = 53, .weight = 180});
  vector_push(links + 53, (Link) {.to = 52, .weight = 180});
  vector_push(links + 53, (Link) {.to = 54, .weight = 120});
  vector_push(links + 54, (Link) {.to = 53, .weight = 120});
  vector_push(links + 55, (Link) {.to = 56, .weight = 180});
  vector_push(links + 56, (Link) {.to = 55, .weight = 180});
  vector_push(links + 56, (Link) {.to = 57, .weight = 180});
  vector_push(links + 57, (Link) {.to = 56, .weight = 180});
  vector_push(links + 57, (Link) {.to = 58, .weight = 240});
  vector_push(links + 58, (Link) {.to = 57, .weight = 240});
  vector_push(links + 58, (Link) {.to = 59, .weight = 120});
  vector_push(links + 59, (Link) {.to = 58, .weight = 120});
  vector_push(links + 59, (Link) {.to = 64, .weight = 200});
  vector_push(links + 64, (Link) {.to = 59, .weight = 200});
  vector_push(links + 64, (Link) {.to = 60, .weight = 160});
  vector_push(links + 60, (Link) {.to = 64, .weight = 160});
  vector_push(links + 60, (Link) {.to = 61, .weight = 240});
  vector_push(links + 61, (Link) {.to = 60, .weight = 240});
  vector_push(links + 61, (Link) {.to = 63, .weight = 170});
  vector_push(links + 63, (Link) {.to = 61, .weight = 170});
  vector_push(links + 63, (Link) {.to = 62, .weight = 150});
  vector_push(links + 62, (Link) {.to = 63, .weight = 150});
  vector_push(links + 62, (Link) {.to = 65, .weight = 180});
  vector_push(links + 65, (Link) {.to = 62, .weight = 180});
  vector_push(links + 65, (Link) {.to = 66, .weight = 180});
  vector_push(links + 66, (Link) {.to = 65, .weight = 180});

  graph_index = malloc(stationlen * sizeof(uint8_t));
  for(uint8_t i = 0; i < stationlen; i++) {
    graph_index[i] = i;
  }
  graph_index[60] = 64;
  graph_index[61] = 60;
  graph_index[62] = 61;
  graph_index[64] = 62;
}
